"""Hardcoded entity lists for Wikipedia RAG ingestion."""

PEOPLE: list[str] = [
    # Required by HW3
    "Albert Einstein",
    "Marie Curie",
    "Leonardo da Vinci",
    "William Shakespeare",
    "Ada Lovelace",
    "Nikola Tesla",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Taylor Swift",
    "Frida Kahlo",
    # Additional
    "Isaac Newton",
    "Charles Darwin",
    "Galileo Galilei",
    "Stephen Hawking",
    "Aristotle",
    "Cleopatra",
    "Napoleon Bonaparte",
    "Abraham Lincoln",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "Martin Luther King Jr.",
    "Winston Churchill",
    "Julius Caesar",
    "Alexander the Great",
    "Genghis Khan",
    "Confucius",
    "Socrates",
    "Plato",
    "Michelangelo",
    "Ludwig van Beethoven",
    "Wolfgang Amadeus Mozart",
    "Johann Sebastian Bach",
    "Pablo Picasso",
    "Salvador Dali",
    "Vincent van Gogh",
    "Rembrandt",
    "Sigmund Freud",
    "Carl Jung",
    "Albert Camus",
    "Friedrich Nietzsche",
    "Karl Marx",
    "Charles Dickens",
    "Mark Twain",
    "Ernest Hemingway",
    "Virginia Woolf",
    "Edgar Allan Poe",
    "Homer",
    "Dante Alighieri",
    "Marco Polo",
    "Christopher Columbus",
]

PLACES: list[str] = [
    # Required by HW3
    "Eiffel Tower",
    "Great Wall of China",
    "Taj Mahal",
    "Grand Canyon",
    "Machu Picchu",
    "Colosseum",
    "Hagia Sophia",
    "Statue of Liberty",
    "Pyramids of Giza",
    "Mount Everest",
    # Additional
    "Stonehenge",
    "Angkor Wat",
    "Petra",
    "Chichen Itza",
    "Easter Island",
    "Acropolis of Athens",
    "Alhambra",
    "Palace of Versailles",
    "Big Ben",
    "Sydney Opera House",
    "Niagara Falls",
    "Amazon rainforest",
    "Sahara",
    "Serengeti",
    "Victoria Falls",
    "Dead Sea",
    "Galápagos Islands",
    "Santorini",
    "Maldives",
    "Bora Bora",
    "Yellowstone National Park",
    "Great Barrier Reef",
    "Antarctica",
    "Mount Fuji",
    "Mount Kilimanjaro",
    "Patagonia",
    "Nile",
    "Amazon River",
    "Mississippi River",
    "Lake Baikal",
    "Mariana Trench",
    "Aurora borealis",
    "Gobi Desert",
    "Mojave Desert",
    "Atacama Desert",
    "Black Forest",
    "Scottish Highlands",
    "Fiordland",
    "Cappadocia",
    "Pompeii",
]

PEOPLE_LOWER = {p.lower() for p in PEOPLE}
PLACES_LOWER = {p.lower() for p in PLACES}
